export const ALBUMS_FETCH_DATA_SUCCESS = 'ALBUMS_FETCH_DATA_SUCCESS';
export const SET_ACTIVE_ALBUM_SUCCESS = 'SET_ACTIVE_ALBUM_SUCCESS';
export const DELETE_ACTIVE_ALBUM_SUCCESS = 'DELETE_ACTIVE_ALBUM_SUCCESS';